python sac_cont_action.py \
       --exp-name "sac_time_series_test_seq2seq_enc_no_pretrain" \
       --seed 1 \
       --wandb-project_name "soft_limb_rl" \
       --wandb-entity "gsue" \
       --env-id "LimbEnv-v0" \
       --total-timesteps 200 \
       --buffer_size 1000000 \
       --batch_size 2 \
       --learning_starts 10 \
       --config_path "./yaml/no_dom/limb_env_power_vel.yml" \
       --head_type "seq2seq_encoder" \
       --no-freeze_head \
       --no-pretrained_model