python sac_cont_action_time_series.py \
       --exp-name "sac_no_head_100k_power" \
       --seed 1 \
       --wandb-project_name "soft_limb_rl" \
       --wandb-entity "gsue" \
       --env-id "LimbEnv-v0" \
       --total-timesteps 100000 \
       --buffer_size 1000000 \
       --batch_size 256 \
       --learning_starts 1000 \
       --num_envs 10 \
       --config_path "./yaml/no_dom/limb_env_power_vel.yml" \
       --head_type "empty" \

python sac_cont_action_time_series.py \
       --exp-name "sac_mlp_head_100k_power" \
       --seed 1 \
       --wandb-project_name "soft_limb_rl" \
       --wandb-entity "gsue" \
       --env-id "LimbEnv-v0" \
       --total-timesteps 100000 \
       --buffer_size 1000000 \
       --batch_size 256 \
       --learning_starts 1000 \
       --num_envs 10 \
       --config_path "./yaml/no_dom/limb_env_power_vel.yml" \
       --head_type "mlp" \
