python finetuning.py \
        --num_samples 100 \
        --batch_size 10 \
        --epochs 2 \
        --exp_name testing \
        --train_data_path ../ml_data/purple_train_data.csv \
        --test_data_path ../ml_data/purple_test_data.csv \
        --model_path ../model_weights/new_weights/SEQ2SEQ_ATTENTION_b512_e200_s-1_Seq2Seq_len50_LSTM_1722928107 \
        --model_type Seq2Seq \
        --attention true \
        --tag testing